version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vps_db
    ports:
      - "3307:3306"
    volumes:
      - output_data:/var/lib/mysql

  backend:
    build: ./vps-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/vps_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

  frontend:
    build: ./vps-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  output_data:
